on: [push]

name: Build ReARM Dependency-Track Components And Submit Metadata To Reliza ReARM

jobs:
  build-dependency-track:
    permissions:
      contents: read
      id-token: write
    name: Build And Push ReARM Dependency-Track
    runs-on: ubuntu-latest
    steps:
      - name: Build And Push ReARM Dependency-Track
        uses: relizaio/rearm-docker-action@c9b221a61039ba59f8255d2976a62542d2286207 # v1.11.0
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/0c42eaee-5ab9-42fc-8735-f4a53b87d0a9-private
          image_name: rearm-dependency-track
          rearm_api_id: ${{ secrets.REARM_DEPENDECY_TRACK_BACKEND_API_ID }}
          rearm_api_key: ${{ secrets.REARM_DEPENDECY_TRACK_BACKEND_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          enable_sbom: 'true'
          source_code_sbom_type: 'custom'
          enable_public_cosign_sigstore: 'true'
          create_component: 'true'
